
package org.ivoa.vodml.stdtypes;

import java.util.Date;

import org.ivoa.vodml.model.DataTypeInstance;
        


      /**
      * UML PrimitiveType duration :  
      * Represents an interval of time from beginning to end. Is not equivalent to a simple real value indicating the number of seconds (for example). In general a custom mapping to a particular serialisation context must be provided.
      *
      * @author generated by VO-URP tools VO-URP Home
      * @author Laurent Bourges (voparis) / Gerard Lemson (mpe)
      */
      public class Duration extends DataTypeInstance{

        /** string representation */
        private Date from;
        private Date to;

        /**
         * Creates a new duration Primitive Type instance, wrapping a base type.
         *
         * @param v 
         */
        public Duration(Date from, Date to) {
            this.from = from;
            this.to = to;
        }
        public Duration() {
            this.from  = new Date();
            this.to = from;
        }


		@Override
		public String vodmlRef() {
			return "ivoa:duration";
		}

		@Override
		public String vodmlId() {
			return "duration";
		}
		public Date getFrom() {
			return from;
		}
		public void setFrom(Date from) {
			this.from = from;
		}
		public Date getTo() {
			return to;
		}
		public void setTo(Date to) {
			this.to = to;
		}
      }
  